# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'persona.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Persona_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(356, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 271, 110))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nombre_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nombre_lbl.setObjectName("nombre_lbl")
        self.gridLayout.addWidget(self.nombre_lbl, 0, 0, 1, 1)
        self.apellido_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.apellido_lbl.setObjectName("apellido_lbl")
        self.gridLayout.addWidget(self.apellido_lbl, 1, 0, 1, 1)
        self.guardar_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.guardar_btn.setObjectName("guardar_btn")
        self.gridLayout.addWidget(self.guardar_btn, 3, 1, 1, 1)
        self.cancelar_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancelar_btn.setObjectName("cancelar_btn")
        self.gridLayout.addWidget(self.cancelar_btn, 3, 2, 1, 1)
        self.apellido_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.apellido_txt.setObjectName("apellido_txt")
        self.gridLayout.addWidget(self.apellido_txt, 1, 1, 1, 2)
        self.nombre_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nombre_txt.setObjectName("nombre_txt")
        self.gridLayout.addWidget(self.nombre_txt, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 356, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Persona"))
        self.nombre_lbl.setText(_translate("MainWindow", "Nombre:"))
        self.apellido_lbl.setText(_translate("MainWindow", "Apellido:"))
        self.guardar_btn.setText(_translate("MainWindow", "Guardar"))
        self.cancelar_btn.setText(_translate("MainWindow", "Cancelar"))
