# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ventana_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 164)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 0, 464, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nombre_ou = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nombre_ou.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nombre_ou.setFont(font)
        self.nombre_ou.setText("")
        self.nombre_ou.setObjectName("nombre_ou")
        self.gridLayout.addWidget(self.nombre_ou, 0, 2, 1, 2)
        self.cerrar_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cerrar_btn.setObjectName("cerrar_btn")
        self.gridLayout.addWidget(self.cerrar_btn, 3, 3, 1, 1)
        self.apellido_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apellido_lbl.setFont(font)
        self.apellido_lbl.setObjectName("apellido_lbl")
        self.gridLayout.addWidget(self.apellido_lbl, 1, 0, 1, 1)
        self.nombre_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nombre_lbl.setFont(font)
        self.nombre_lbl.setObjectName("nombre_lbl")
        self.gridLayout.addWidget(self.nombre_lbl, 0, 0, 1, 1)
        self.actualizar_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.actualizar_btn.setObjectName("actualizar_btn")
        self.gridLayout.addWidget(self.actualizar_btn, 3, 2, 1, 1)
        self.apellido_ou = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apellido_ou.setFont(font)
        self.apellido_ou.setText("")
        self.apellido_ou.setObjectName("apellido_ou")
        self.gridLayout.addWidget(self.apellido_ou, 1, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana - Persona"))
        self.cerrar_btn.setText(_translate("MainWindow", "Cerrar"))
        self.apellido_lbl.setText(_translate("MainWindow", "Apellido:"))
        self.nombre_lbl.setText(_translate("MainWindow", "Nombre:"))
        self.actualizar_btn.setText(_translate("MainWindow", "Actualizar"))
